server:
  port: 9000

security:
  oauth2:
    client:
      client-id: 682491403304768
      client-secret: 40e929cbe418ea0345d6464288e891e7
      access-token-uri: https://graph.facebook.com/oauth/access_token
      user-authorization-uri: https://www.facebook.com/dialog/oauth
      token-name: oauth_token
      authentication-scheme: query
      client-authentication-scheme: form
    resource:
      user-info-uri: https://graph.facebook.com//me
